version: '3.8'

  db:
    image: mysql:5.7
    container_name: todo-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todolist
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network
    services:
  app:
    build: .
    container_name: todo-app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mysql-data:
